# Generated by Django 2.1.4 on 2019-01-27 17:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WGB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='send_datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 17, 48, 18, 977199, tzinfo=utc), verbose_name='送信日時'),
        ),
        migrations.AlterField(
            model_name='threads',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 27, 17, 48, 18, 961574, tzinfo=utc), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='threadwrite',
            name='write_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='書き込み日時'),
        ),
    ]
