# Generated by Django 2.1.3 on 2018-11-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WGB', '0002_auto_20181126_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='threads',
            name='open_level',
            field=models.SmallIntegerField(choices=[(0, '非公開'), (1, '閲覧のみ'), (2, '閲覧・書き込みとも')], default=1, verbose_name='公開レベル'),
            preserve_default=False,
        ),
    ]
