# Generated by Django 2.1.3 on 2018-11-27 04:43

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('WGB', '0003_threads_open_level'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='AccountSub',
        # ),
        migrations.AddField(
            model_name='threadmember',
            name='create',
            field=models.BooleanField(default=False, verbose_name='掲示板作成者フラグ'),
        ),
    ]
