# Generated by Django 2.1.3 on 2018-11-27 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WGB', '0006_useraccount_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WGB.ThreadMember', verbose_name='参加メンバー'),
        ),
        migrations.AlterField(
            model_name='threadwrite',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WGB.ThreadMember', verbose_name='参加メンバー'),
        ),
    ]
