# Generated by Django 2.1.3 on 2018-11-27 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WGB', '0007_auto_20181127_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directmessage',
            options={'verbose_name': 'メッセージ', 'verbose_name_plural': '3.ダイレクトメッセージ'},
        ),
    ]
