# Generated by Django 2.1.3 on 2018-11-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WGB', '0008_auto_20181127_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='message',
            field=models.TextField(max_length=5000, verbose_name='メッセージ'),
        ),
    ]
