# Generated by Django 2.1.3 on 2018-11-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WGB', '0009_auto_20181127_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directmessageattachment',
            options={'verbose_name': 'メッセージ添付ファイル', 'verbose_name_plural': '添付ファイル'},
        ),
        migrations.AlterModelOptions(
            name='threadmember',
            options={'verbose_name': '掲示板参加メンバー', 'verbose_name_plural': '参加メンバー'},
        ),
        migrations.AlterModelOptions(
            name='threadwriteattachment',
            options={'verbose_name': '書き込み添付ファイル', 'verbose_name_plural': '添付ファイル'},
        ),
    ]
