# Generated by Django 2.1.3 on 2018-11-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WGB', '0010_auto_20181127_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessageattachment',
            name='attachment',
            field=models.FileField(upload_to='attachment_messages/', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='threads',
            name='open_level',
            field=models.SmallIntegerField(choices=[(0, '非公開(パスワードがないと閲覧・書き込み不可)'), (1, '閲覧のみ(パスワードがないと書き込み不可)'), (2, '閲覧・書き込みとも可能')], verbose_name='公開レベル'),
        ),
        migrations.AlterField(
            model_name='threadwriteattachment',
            name='attachment',
            field=models.FileField(upload_to='attachments/', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='icon',
            field=models.ImageField(upload_to='icons/', verbose_name='アイコン画像パス'),
        ),
    ]
