# Generated by Django 2.1.3 on 2018-11-28 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WGB', '0011_auto_20181128_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threads',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 28, 6, 34, 26, 865932), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='threads',
            name='thread_no',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='掲示板No'),
        ),
    ]
