# Generated by Django 2.1.3 on 2018-11-28 06:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WGB', '0012_auto_20181128_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threads',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 28, 6, 35, 40, 584125, tzinfo=utc), verbose_name='作成日時'),
        ),
    ]
