# Generated by Django 2.1.3 on 2018-11-28 08:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WGB', '0013_auto_20181128_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadwrite',
            name='write_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 28, 8, 32, 2, 79754, tzinfo=utc), verbose_name='書き込み日時'),
        ),
        migrations.AlterField(
            model_name='threads',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 28, 8, 32, 2, 78823, tzinfo=utc), verbose_name='作成日時'),
        ),
    ]
