# Generated by Django 2.1.3 on 2018-11-30 02:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WGB', '0016_auto_20181129_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threads',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 2, 45, 13, 553173, tzinfo=utc), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='threads',
            name='open_level',
            field=models.SmallIntegerField(choices=[(0, '非公開<br/>(参加しないと閲覧・書き込み不可)'), (1, '閲覧のみ<br/>(参加しないと書き込み不可)'), (2, '閲覧・書き込み可能<br/>(参加は任意)')], verbose_name='公開レベル'),
        ),
        migrations.AlterField(
            model_name='threadwrite',
            name='write_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 2, 45, 13, 555173, tzinfo=utc), verbose_name='書き込み日時'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/', verbose_name='アイコン画像パス'),
        ),
    ]
