# Generated by Django 2.1.3 on 2018-11-30 05:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WGB', '0017_auto_20181130_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WGB.Threads', verbose_name='掲示板スレッド')),
                ('sequence', models.IntegerField(verbose_name='連番')),
                ('message', models.TextField(max_length=5000, verbose_name='メッセージ')),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_member', to='WGB.ThreadMember', verbose_name='送信者')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_member', to='WGB.ThreadMember', verbose_name='送信相手')),
            ],
            options={
                'verbose_name': 'メッセージ',
                'verbose_name_plural': '3.ダイレクトメッセージ',
                'db_table': 'direct_message',
            },
        ),
        migrations.CreateModel(
            name='DirectMessageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(verbose_name='連番')),
                ('attachment', models.FileField(upload_to='attachment_messages/', verbose_name='添付ファイル')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WGB.DirectMessage', verbose_name='メッセージ')),
            ],
            options={
                'verbose_name': 'メッセージ添付ファイル',
                'verbose_name_plural': '添付ファイル',
                'db_table': 'direct_message_attachment',
            },
        ),
        migrations.AlterUniqueTogether(
            name='directmessageattachment',
            unique_together={('message', 'sequence')},
        ),
        migrations.AlterUniqueTogether(
            name='directmessage',
            unique_together={('thread', 'from_member', 'to_member', 'sequence')},
        ),
        migrations.AlterField(
            model_name='threads',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 5, 1, 53, 125000, tzinfo=utc), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='threadwrite',
            name='write_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 5, 1, 53, 126000, tzinfo=utc), verbose_name='書き込み日時'),
        ),
    ]
