# Generated by Django 2.1.3 on 2018-11-30 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WGB', '0019_auto_20181130_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threads',
            name='password_require',
        ),
        migrations.AlterField(
            model_name='threads',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 7, 20, 13, 609000, tzinfo=utc), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='threads',
            name='open_level',
            field=models.SmallIntegerField(choices=[(0, '非公開<br/>(参加しないと閲覧・書き込み不可)'), (1, '閲覧のみ<br/>(参加しないと書き込み不可)')], verbose_name='公開レベル'),
        ),
        migrations.AlterField(
            model_name='threads',
            name='password',
            field=models.CharField(default=1, max_length=100, verbose_name='利用パスワード'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='threadwrite',
            name='write_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 7, 20, 13, 610000, tzinfo=utc), verbose_name='書き込み日時'),
        ),
    ]
