# Generated by Django 2.1.3 on 2018-11-30 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WGB', '0020_auto_20181130_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='send_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 8, 35, 30, 6000, tzinfo=utc), verbose_name='送信日時'),
        ),
        migrations.AlterField(
            model_name='threads',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 8, 35, 30, 4000, tzinfo=utc), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='threads',
            name='open_level',
            field=models.SmallIntegerField(choices=[(0, '非公開 (参加者のみ閲覧・書き込み可)'), (1, '閲覧のみ (参加者のみ書き込み可)')], verbose_name='公開レベル'),
        ),
        migrations.AlterField(
            model_name='threadwrite',
            name='write_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 8, 35, 30, 5000, tzinfo=utc), verbose_name='書き込み日時'),
        ),
    ]
