# Generated by Django 2.1.3 on 2018-12-03 06:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WGB', '0021_auto_20181130_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='タイトル'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='send_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 6, 21, 42, 801603, tzinfo=utc), verbose_name='送信日時'),
        ),
        migrations.AlterField(
            model_name='threads',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 6, 21, 42, 797603, tzinfo=utc), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='threadwrite',
            name='write_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 6, 21, 42, 798603, tzinfo=utc), verbose_name='書き込み日時'),
        ),
    ]
