# Generated by Django 2.1.3 on 2018-12-03 06:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WGB', '0022_auto_20181203_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='send_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 6, 47, 38, 3603, tzinfo=utc), verbose_name='送信日時'),
        ),
        migrations.AlterField(
            model_name='threads',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 6, 47, 38, 603, tzinfo=utc), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='threadwrite',
            name='write_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 6, 47, 38, 2603, tzinfo=utc), verbose_name='書き込み日時'),
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='thread',
        ),
        migrations.AlterUniqueTogether(
            name='directmessage',
            unique_together={('from_member', 'to_member')},
        ),
    ]
