# Generated by Django 2.1.3 on 2018-12-03 07:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WGB', '0023_auto_20181203_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directmessage',
            options={'get_latest_by': ('from_member', 'to_member', 'sequence'), 'verbose_name': 'メッセージ', 'verbose_name_plural': '3.ダイレクトメッセージ'},
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='send_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 7, 22, 14, 876603, tzinfo=utc), verbose_name='送信日時'),
        ),
        migrations.AlterField(
            model_name='threads',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 7, 22, 14, 874603, tzinfo=utc), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='threadwrite',
            name='write_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 3, 7, 22, 14, 875603, tzinfo=utc), verbose_name='書き込み日時'),
        ),
        migrations.AlterUniqueTogether(
            name='directmessage',
            unique_together={('from_member', 'to_member', 'sequence')},
        ),
    ]
