# Generated by Django 2.1.3 on 2018-12-06 07:44

import WGB.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WGB', '0024_auto_20181203_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='send_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 6, 7, 44, 16, 244000, tzinfo=utc), verbose_name='送信日時'),
        ),
        migrations.AlterField(
            model_name='directmessageattachment',
            name='attachment',
            field=models.ImageField(upload_to=WGB.models.get_upload_to, verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='threads',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 6, 7, 44, 16, 242000, tzinfo=utc), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='threadwrite',
            name='write_datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 6, 7, 44, 16, 243000, tzinfo=utc), verbose_name='書き込み日時'),
        ),
        migrations.AlterField(
            model_name='threadwriteattachment',
            name='attachment',
            field=models.ImageField(upload_to=WGB.models.get_upload_to, verbose_name='添付画像ファイル'),
        ),
    ]
